from __future__ import annotations

import html as html_module
import re
from collections import defaultdict
from datetime import date, timedelta
from pathlib import Path
from typing import Any

from mc import config as cfg
from mc import digest as digest_mod
from mc import sync
from mc.plan import PlanLock

# --- markdown -> HTML -------------------------------------------------------------
# Handwritten, dependency-free subset parser (not a general markdown lib) --
# deliberately scoped to what this project's own generators actually emit
# (headers, tables, bold/italic/code/links, hr, blockquotes, unordered
# lists, paragraphs), since every .md in this repo is generated by our own
# code, not arbitrary user-authored markdown.

PAGE_CSS = """
  :root { color-scheme: light dark; }
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
         max-width: 820px; margin: 0 auto; padding: 1.25rem; line-height: 1.5; }
  h1 { font-size: 1.3rem; margin-bottom: 0.3rem; }
  h2 { font-size: 1.05rem; margin-top: 1.75rem; border-bottom: 1px solid currentColor; padding-bottom: 0.2rem; }
  h3 { font-size: 0.95rem; margin-top: 1.25rem; }
  table { width: 100%; border-collapse: collapse; margin: 0.75rem 0; font-size: 0.85rem; }
  th, td { text-align: left; padding: 0.35rem 0.5rem; border-bottom: 1px solid rgba(128,128,128,0.3); }
  th { font-weight: 600; }
  blockquote { margin: 0.75rem 0; padding: 0.5rem 0.9rem; border-left: 3px solid rgba(128,128,128,0.5); opacity: 0.9; }
  code { font-size: 0.85em; background: rgba(128,128,128,0.15); padding: 0.1em 0.3em; border-radius: 3px; }
  hr { border: none; border-top: 1px solid rgba(128,128,128,0.3); margin: 1.5rem 0; }
  ul { padding-left: 1.2rem; }
  li { margin-bottom: 0.3rem; }
  a { color: inherit; }
  .bar-track { background: rgba(128,128,128,0.15); border-radius: 3px; overflow: hidden; height: 10px; width: 100%; }
  .bar-fill { height: 100%; }
  .stat { font-size: 2rem; font-weight: 700; }
  .stat-label { opacity: 0.7; font-size: 0.85rem; }
"""

_TABLE_SEP_RE = re.compile(r"^\s*\|[\s:|-]+\|\s*$")
_HEADER_RE = re.compile(r"(#{1,6})\s+(.*)")
_HR_RE = re.compile(r"-{3,}")
_UL_RE = re.compile(r"[-*]\s+")


def _inline(text: str) -> str:
    text = html_module.escape(text, quote=False)
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"(?<!\*)\*([^*]+?)\*(?!\*)", r"<em>\1</em>", text)
    text = re.sub(r"`([^`]+?)`", r"<code>\1</code>", text)
    text = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r'<a href="\2">\1</a>', text)
    return text


def markdown_to_html_body(md_text: str) -> str:
    lines = md_text.splitlines()
    out: list[str] = []
    i = 0
    in_list = False

    def close_list():
        nonlocal in_list
        if in_list:
            out.append("</ul>")
            in_list = False

    while i < len(lines):
        stripped = lines[i].strip()

        if not stripped:
            close_list()
            i += 1
            continue

        if _HR_RE.fullmatch(stripped):
            close_list()
            out.append("<hr>")
            i += 1
            continue

        m = _HEADER_RE.match(stripped)
        if m:
            close_list()
            level = len(m.group(1))
            out.append(f"<h{level}>{_inline(m.group(2))}</h{level}>")
            i += 1
            continue

        if stripped.startswith("|") and i + 1 < len(lines) and _TABLE_SEP_RE.match(lines[i + 1]):
            close_list()
            headers = [c.strip() for c in stripped.strip("|").split("|")]
            out.append("<table><tr>" + "".join(f"<th>{_inline(h)}</th>" for h in headers) + "</tr>")
            i += 2
            while i < len(lines) and lines[i].strip().startswith("|"):
                cells = [c.strip() for c in lines[i].strip().strip("|").split("|")]
                out.append("<tr>" + "".join(f"<td>{_inline(c)}</td>" for c in cells) + "</tr>")
                i += 1
            out.append("</table>")
            continue

        if stripped.startswith(">"):
            close_list()
            out.append(f"<blockquote>{_inline(stripped.lstrip('>').strip())}</blockquote>")
            i += 1
            continue

        if _UL_RE.match(stripped):
            if not in_list:
                out.append("<ul>")
                in_list = True
            out.append(f"<li>{_inline(_UL_RE.sub('', stripped, count=1))}</li>")
            i += 1
            continue

        close_list()
        out.append(f"<p>{_inline(stripped)}</p>")
        i += 1

    close_list()
    return "\n".join(out)


def _extract_title(md_text: str) -> str | None:
    m = re.search(r"^#\s+(.*)$", md_text, re.MULTILINE)
    return m.group(1).strip() if m else None


def render_markdown(md_text: str, title: str | None = None, extra_style: str = "") -> str:
    title = title or _extract_title(md_text) or "mc"
    body = markdown_to_html_body(md_text)
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{html_module.escape(title)}</title>
<style>{PAGE_CSS}{extra_style}</style>
</head>
<body>
{body}
</body>
</html>
"""


def render_file(md_path: Path) -> Path:
    html_text = render_markdown(md_path.read_text())
    html_path = md_path.with_suffix(".html")
    html_path.write_text(html_text)
    return html_path


# out/tomorrow.md is a *provisional* projection written by /preview the
# evening before. It goes stale the moment its target date passes, and a
# stale one is worse than none: render_all would happily turn yesterday's
# guess into a fresh-looking HTML page indistinguishable from a real plan.
# Same precedent as push._check_today_md_date -- the file states which day it
# is for, and we believe the file rather than its filename.
PROVISIONAL_FILES = {"tomorrow.md"}
_HEADER_DATE_RE = re.compile(r"^#\s*(\d{2}-\d{2})", re.MULTILINE)


def target_date_of(md_path: Path) -> str | None:
    """The DD-MM in the file's own `# DD-MM · ...` header, if any."""
    match = _HEADER_DATE_RE.search(md_path.read_text())
    return match.group(1) if match else None


def is_stale(md_path: Path, as_of: date | None = None) -> bool:
    """True when a provisional file's own header date is in the past."""
    if md_path.name not in PROVISIONAL_FILES:
        return False
    header = target_date_of(md_path)
    if header is None:
        return True  # a provisional file that won't say which day it's for is not trustworthy
    as_of = as_of or date.today()
    return header != as_of.strftime("%d-%m") and header != (as_of + timedelta(days=1)).strftime("%d-%m")


def render_all(out_dir: Path = cfg.OUT_DIR, as_of: date | None = None) -> tuple[list[Path], list[Path]]:
    """Returns (rendered, skipped). Skipped are stale provisional files."""
    if not out_dir.exists():
        return [], []
    rendered, skipped = [], []
    for p in sorted(out_dir.glob("*.md")):
        if is_stale(p, as_of):
            skipped.append(p)
        else:
            rendered.append(render_file(p))
    return rendered, skipped


# --- dashboard.html -----------------------------------------------------------------
# No markdown source (see §2 file tree — dashboard.html has no dashboard.md
# twin) since this is a data visualization, not a document.


def _bar(pct: float, color: str = "currentColor") -> str:
    width = max(0, min(100, pct * 100))
    return (
        f'<div class="bar-track"><div class="bar-fill" '
        f'style="width:{width:.0f}%;background:{color}"></div></div>'
    )


def _actuals_by_week(
    plan: PlanLock, garmin_activities: list[dict[str, Any]], as_of: date | None = None
) -> dict[int, dict[str, Any]]:
    as_of = as_of or date.today()
    result: dict[int, dict[str, Any]] = {}
    for week in plan.weeks:
        actuals = digest_mod.actuals_for_plan_week(
            garmin_activities, week.wc, week.wc + timedelta(days=6), as_of=as_of
        )
        result[week.week] = {
            "long_run": actuals.long_run_mi,
            "run_miles": actuals.run_miles,
            "run_days": actuals.run_days,
            "has_started": actuals.has_started,
        }
    return result


# Hal Higdon Marathon Intermediate 1, verbatim, unedited (plan/plan-source.md)
# — (long_run_mi, weekly_volume_mi) per original week 1-18. Half marathon
# (wk9) and marathon (wk18) counted as their race distance / excluded from
# volume respectively, not as a training long run.
HIGDON_ORIGINAL: dict[int, tuple[float, float]] = {
    1: (8, 24), 2: (9, 25), 3: (6, 22), 4: (11, 29), 5: (12, 30),
    6: (9, 26), 7: (14, 36), 8: (15, 37), 9: (13.1, 26.1), 10: (17, 41),
    11: (18, 44), 12: (13, 36), 13: (20, 43), 14: (12, 35), 15: (20, 43),
    16: (12, 32), 17: (8, 24), 18: (0, 9),
}


def build_dashboard_html(plan: PlanLock, garmin_activities: list[dict[str, Any]], as_of: date | None = None) -> str:
    as_of = as_of or date.today()
    weeks_to_race = max(0, (plan.race_date - as_of).days // 7)
    actuals = _actuals_by_week(plan, garmin_activities, as_of=as_of)

    rows = []
    for week in plan.weeks:
        act = actuals[week.week]
        started = act["has_started"]
        long_run_pct = (act["long_run"] / week.long_run_mi) if started and week.long_run_mi else 0
        vol_pct = (act["run_miles"] / week.run_miles) if started and week.run_miles else 0
        is_travel = week.block == "travel_italy"
        row_style = ' style="background:rgba(255,180,0,0.08)"' if is_travel else ""
        week_to_event = max(0, (plan.race_date - week.wc).days // 7)
        # Aligned on marathon week, not row index: Higdon's plan is 18 weeks,
        # ours is 14, both end race week -- so our week N lines up with his
        # week N+4 (his weeks 1-4 have no equivalent in the compressed plan).
        higdon = HIGDON_ORIGINAL.get(week.week + 4)
        higdon_long = f"{higdon[0]:g}mi" if higdon else "—"
        higdon_vol = f"{higdon[1]:g}mi" if higdon else "—"
        rows.append(
            f"""<tr{row_style}>
  <td>Week {week.week} · w/c {week.wc.strftime('%d-%m')}</td>
  <td>{week_to_event}</td>
  <td>{week.block}</td>
  <td>{week.long_run_mi:g}mi planned / {act['long_run'] if started else '—'}{'mi' if started else ''} actual
      {_bar(long_run_pct) if started else ''}</td>
  <td>{week.run_miles:g}mi / {act['run_miles'] if started else '—'}{'mi' if started else ''}
      {_bar(vol_pct) if started else ''}</td>
  <td>{week.run_days}d planned / {act['run_days'] if started else '—'}{'d' if started else ''}</td>
  <td>{higdon_long}</td>
  <td>{higdon_vol}</td>
</tr>"""
        )

    travel_weeks = [w for w in plan.weeks if w.block == "travel_italy"]
    travel_range = ""
    if travel_weeks:
        start = travel_weeks[0].wc.strftime("%d-%m")
        end = (travel_weeks[-1].wc + timedelta(days=6)).strftime("%d-%m")
        travel_range = f"{start} → {end}"

    body = f"""<h1>Marathon 2026 — dashboard</h1>
<p class="stat-label">as of {as_of.strftime('%d-%m-%Y')}</p>

<div class="stat">{weeks_to_race}</div>
<div class="stat-label">weeks to race ({plan.race_date.strftime('%d-%m-%Y')})</div>

<h2>Travel block</h2>
<p>{travel_range or 'none'} — opportunistic long run, no quality, no gym (bodyweight only)</p>

<h2>Plan vs actual, week by week</h2>
<p class="stat-label">"Higdon Long"/"Higdon weekly volume" are Hal Higdon's
original Intermediate 1 plan (plan/plan-source.md), unedited, aligned on
marathon week: his 18-week plan and this 14-week one both end race week, so
our week N lines up with his week N+4 (his weeks 1-4 have no equivalent
here). Not the same as what this plan explicitly borrows from Higdon week-
for-week (see each week's <code>source_week</code> in plan.lock.json) — this
is just a fixed same-distance-to-race reference point.</p>
<table>
  <tr>
    <th>Week</th><th>Week to event</th><th>Block</th><th>Long run</th>
    <th>Weekly volume</th><th>Run days</th>
    <th>Higdon Long</th><th>Higdon weekly volume</th>
  </tr>
  {"".join(rows)}
</table>
"""
    return render_markdown_fragment(body, title="Marathon 2026 — dashboard")


def render_markdown_fragment(body_html: str, title: str) -> str:
    """Like render_markdown but for pre-built HTML (dashboard), not markdown source."""
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{html_module.escape(title)}</title>
<style>{PAGE_CSS}</style>
</head>
<body>
{body_html}
</body>
</html>
"""


def write_dashboard(plan: PlanLock, garmin_activities: list[dict[str, Any]], as_of: date | None = None) -> Path:
    cfg.OUT_DIR.mkdir(parents=True, exist_ok=True)
    html_text = build_dashboard_html(plan, garmin_activities, as_of)
    path = cfg.OUT_DIR / "dashboard.html"
    path.write_text(html_text)
    return path
